##
## "HLS.XION.MT"
## XionHLS live streaming portal
##

server
{
	include /etc/nginx/sitebits.conf;
	ssl_certificate /etc/letsencrypt/live/hls.xion.mt/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/hls.xion.mt/privkey.pem;
	server_name hls.xion.mt;
	gzip on;

	root /var/lib/nginx/public/mt.xion.hls;
}

server
{
	server_name hls.xion.mt;
	include /etc/nginx/ssl-redirect.conf;
}
