##
## "KB.XION.MT"
## XionKB company wiki
##

server
{
	include /etc/nginx/sitebits.conf;
	ssl_certificate /etc/letsencrypt/live/kb.xion.mt/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/kb.xion.mt/privkey.pem;
	server_name kb.xion.mt;
	gzip on;

	root /var/lib/nginx/public/mt.xion.kb;

	include /etc/nginx/enabled.authed/mt.xion.kb.conf;
}

server
{
	server_name kb.xion.mt;
	include /etc/nginx/ssl-redirect.conf;
}
