##
## "XION.MT"
## Xion Megatrends landing page
##

server
{
	include /etc/nginx/sitebits.conf;
	ssl_certificate /etc/letsencrypt/live/xion.mt/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/xion.mt/privkey.pem;
	server_name xion.mt;

	root /var/lib/nginx/public/mt.xion;
}

server
{
	server_name xion.mt;
	include /etc/nginx/ssl-redirect.conf;
}

server
{
	listen 80;
	include /etc/nginx/website-bits.conf;
	ssl_certificate /etc/letsencrypt/live/xion.mt/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/xion.mt/privkey.pem;
	server_name www.xion.mt;

	return 307 https://xion.mt$request_uri;
}
