##
## "CDN.XION.MT"
## XionCDN file host
##

server
{
	include /etc/nginx/sitebits.conf;
	ssl_certificate /etc/letsencrypt/live/cdn.xion.mt/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/cdn.xion.mt/privkey.pem;
	server_name cdn.xion.mt;
	gzip on;

	root /var/lib/nginx/public/mt.xion.cdn;
	ssi off;

	location /
	{
		return 403;
	}

	include /etc/nginx/private/mt.xion.cdn.conf;
}

server
{
	server_name cdn.xion.mt;
	include /etc/nginx/ssl-redirect.conf;
}
