##
## "BT.XION.MT"
## XionBT torrent tracker
##

server
{
	include /etc/nginx/sitebits.conf;
	ssl_certificate /etc/letsencrypt/live/bt.xion.mt/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/bt.xion.mt/privkey.pem;
	server_name bt.xion.mt;
	gzip on;

	root /var/lib/nginx/public/mt.xion.bt;
}

server
{
	server_name bt.xion.mt;
	include /etc/nginx/ssl-redirect.conf;
}
