##
## "MAB.XION.MT"
## XionMAB multi-author weblog
##

server
{
	include /etc/nginx/sitebits.conf;
	ssl_certificate /etc/letsencrypt/live/mab.xion.mt/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/mab.xion.mt/privkey.pem;
	server_name mab.xion.mt;
	gzip on;

	root /var/lib/nginx/public/mt.xion.mab;
}

server
{
	server_name mab.xion.mt;
	include /etc/nginx/ssl-redirect.conf;
}
