##
## "SYMVER.ORG"
## Symbolic Versioning website
##

server
{
	include /etc/nginx/sitebits.conf;
	ssl_certificate /etc/letsencrypt/live/symver.org/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/symver.org/privkey.pem;
	server_name symver.org;
	gzip on;

	root /var/lib/nginx/public/org.symver;
}

server
{
	server_name symver.org;
	include /etc/nginx/ssl-redirect.conf;
}

server
{
	listen 80;
	include /etc/nginx/sitebits.conf;
	ssl_certificate /etc/letsencrypt/live/symver.org/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/symver.org/privkey.pem;
	server_name www.symver.org;

	return 307 https://symver.org$request_uri;
}
