listen [::]:443 ssl;
listen 443 ssl;

include /etc/nginx/letsencrypt-ssl.conf;
include /etc/nginx/mime.types;
ssl_dhparam /etc/nginx/letsencrypt-dhparams.pem;
add_header Strict-Transport-Security "max-age=31536000" always;
# no POSTing unless I say so
add_header Access-Control-Allow-Methods GET;
default_type text/html;
index index.html index.htm index.txt;
gzip_static on;
gzip_min_length 250;
gunzip on;
gzip_types
	text/css
	text/plain
	text/tab-separated-values
	text/csv
	text/x-rst
	application/x-perl
	application/json
	application/javascript
	text/javascript
	application/x-sh
	text/x-asm
	text/x-c
	text/x-c++src
	text/x-c++hdr
	text/x-objcsrc
	text/x-csharp
	text/x-fortran
	text/x-go
	text/x-java-source
	text/markdown
	text/x-python
	text/x-scala
	application/sql
	text/typescript
	application/atom+xml
	application/rss+xml
	image/svg+xml;

location ~* \.(css|js|json|eot|[to]tf|woff2?|jpe?g|gif|png|svg|mp[4g])$
{
	add_header Access-Control-Allow-Origin *;
	add_header Access-Control-Allow-Methods GET;
	add_header Cache-Control public;
	expires 7d;
}

location ~ /(\..+|.+~|\#.*\#)$
{
	return 403;
}
