listen [::]:443 ssl;
listen 443 ssl;

include /etc/nginx/letsencrypt-ssl.conf;
include /etc/nginx/mime.types;
ssl_dhparam /etc/nginx/letsencrypt-dhparams.pem;
add_header Strict-Transport-Security "max-age=31536000" always;
# no POSTing unless I say so
add_header Access-Control-Allow-Methods GET;
default_type text/html;
index index.html index.htm index.txt;
gzip_static on;
gzip_min_length 250;
gunzip on;
gzip_types
	text/css
	text/plain
	text/tab-separated-values
	text/csv
	text/x-rst
	application/x-perl
	application/json
	application/javascript
	text/javascript
	application/x-sh
	text/x-asm
	text/x-c
	text/x-c++src
	text/x-c++hdr
	text/x-objcsrc
	text/x-csharp
	text/x-fortran
	text/x-go
	text/x-java-source
	text/markdown
	text/x-python
	text/x-scala
	application/sql
	text/typescript
	application/atom+xml
	application/rss+xml
	image/svg+xml;

location ~* \.(css|js|json|eot|[to]tf|woff2?|jpe?g|gif|png|svg|mp[4g])$
{
	add_header Access-Control-Allow-Origin *;
	add_header Access-Control-Allow-Methods GET;
	add_header Cache-Control public;
	expires 7d;
}

# Error pages configuration
error_page 400 /.err/400.html;
error_page 401 /.err/401.html;
error_page 403 /.err/403.html;
error_page 404 /.err/404.html;
error_page 405 /.err/405.html;
error_page 408 /.err/408.html;
error_page 418 /.err/418.html;
error_page 429 /.err/429.html;
error_page 451 /.err/451.html;
error_page 500 /.err/500.html;
error_page 501 /.err/501.html;
error_page 502 /.err/502.html;
error_page 503 /.err/503.html;
error_page 504 /.err/504.html;
error_page 505 /.err/505.html;

# Maintenance configuration
# Uncomment the following line when maintenance is needed
# return 503 /.err/maintenance.html;

# Enable error page interception for proxy passthrough
proxy_intercept_errors on;

# Location for error pages
location ^~ /.err/
{
	internal;
	alias /var/lib/nginx/errorpages/;
	try_files $uri =404;
}

location ~ /(\..+|.+~|\#.*\#)$
{
	return 403;
}
